@echo off
echo Building Release R20...
dotnet build RincoNhan.csproj -c "Release R20"
echo Building Release R21...
dotnet build RincoNhan.csproj -c "Release R21"
echo Building Release R22...
dotnet build RincoNhan.csproj -c "Release R22"
echo Building Release R23...
dotnet build RincoNhan.csproj -c "Release R23"
echo Building Release R24...
dotnet build RincoNhan.csproj -c "Release R24"
echo Building Release R25...
dotnet build RincoNhan.csproj -c "Release R25"
echo Building Release R26...
dotnet build RincoNhan.csproj -c "Release R26"
echo Build complete.
